/// Flutter icons Cedmate
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Cedmate
///      fonts:
///       - asset: fonts/Cedmate.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Cedmate {
  Cedmate._();

  static const _kFontFam = 'Cedmate';
  static const String? _kFontPkg = null;

  static const IconData kons_6 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kons_5 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kons_4 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kons_7 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kons_3 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kons_2 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kons_1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
