// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjcJbObLeROEa0zuH6qrhNR5KhmFM8S84',
    appId: '1:428216500561:web:7c15eab3b45393fb8d1370',
    messagingSenderId: '428216500561',
    projectId: 'cedmate-b63a2',
    authDomain: 'cedmate-b63a2.firebaseapp.com',
    storageBucket: 'cedmate-b63a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuJe07rbTekOo7KgYixkzV7pbmYRayFzg',
    appId: '1:428216500561:android:b929b428627c7f518d1370',
    messagingSenderId: '428216500561',
    projectId: 'cedmate-b63a2',
    storageBucket: 'cedmate-b63a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Vy6cRontkMjZt7KXsSdFgUip0CmVIU8',
    appId: '1:428216500561:ios:b8a961ded191e1418d1370',
    messagingSenderId: '428216500561',
    projectId: 'cedmate-b63a2',
    storageBucket: 'cedmate-b63a2.firebasestorage.app',
    iosBundleId: 'com.example.cedmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Vy6cRontkMjZt7KXsSdFgUip0CmVIU8',
    appId: '1:428216500561:ios:b8a961ded191e1418d1370',
    messagingSenderId: '428216500561',
    projectId: 'cedmate-b63a2',
    storageBucket: 'cedmate-b63a2.firebasestorage.app',
    iosBundleId: 'com.example.cedmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjcJbObLeROEa0zuH6qrhNR5KhmFM8S84',
    appId: '1:428216500561:web:787c0a0db13947508d1370',
    messagingSenderId: '428216500561',
    projectId: 'cedmate-b63a2',
    authDomain: 'cedmate-b63a2.firebaseapp.com',
    storageBucket: 'cedmate-b63a2.firebasestorage.app',
  );
}
