// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvK8yc4HUVyx01FXBfI10GnvScibIwiXg',
    appId: '1:1089891052869:web:95ba1de2b19b504654a22c',
    messagingSenderId: '1089891052869',
    projectId: 'cedmate-9c78b',
    authDomain: 'cedmate-9c78b.firebaseapp.com',
    storageBucket: 'cedmate-9c78b.firebasestorage.app',
    measurementId: 'G-2ZX4F8E7PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSf3NKvZzoJf19jHVlt2LF_W1x_8ZI2uI',
    appId: '1:1089891052869:android:44e2dac55206eb9654a22c',
    messagingSenderId: '1089891052869',
    projectId: 'cedmate-9c78b',
    storageBucket: 'cedmate-9c78b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjWasZxbMH71XgzpLTPGUhB4FTd3hM5qs',
    appId: '1:1089891052869:ios:74e75aa5614812d154a22c',
    messagingSenderId: '1089891052869',
    projectId: 'cedmate-9c78b',
    storageBucket: 'cedmate-9c78b.firebasestorage.app',
    iosBundleId: 'com.example.cedmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjWasZxbMH71XgzpLTPGUhB4FTd3hM5qs',
    appId: '1:1089891052869:ios:74e75aa5614812d154a22c',
    messagingSenderId: '1089891052869',
    projectId: 'cedmate-9c78b',
    storageBucket: 'cedmate-9c78b.firebasestorage.app',
    iosBundleId: 'com.example.cedmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvK8yc4HUVyx01FXBfI10GnvScibIwiXg',
    appId: '1:1089891052869:web:7a47aca96bedeb6354a22c',
    messagingSenderId: '1089891052869',
    projectId: 'cedmate-9c78b',
    authDomain: 'cedmate-9c78b.firebaseapp.com',
    storageBucket: 'cedmate-9c78b.firebasestorage.app',
    measurementId: 'G-D713J4GSE5',
  );

}